### ISSUE TITLE
mingw32-make.exe: *** [Makefile:100: all] Error 2

### ISSUE THREAD

**Issue by iMountTai** [josStorer/llama.cpp-unicode-windows#2]
![image](https://user-images.githubusercontent.com/35353688/231351338-73b1555e-5c40-4df6-8d3c-021cd214002b.png)
不清楚是什么原因导致的，试过多种方式仍然不能解决

**Comment by josStorer** [comment]
用msvc编译

另外目前官方仓库已经支持中文了, 可以直接用官方仓库了

**Comment by iMountTai** [comment]
官方仓库也会出现这个问题

**Comment by josStorer** [comment]
官方在windows下应该是建议使用cmake生成vs工程, 用msvc编译的

![image](https://user-images.githubusercontent.com/13366013/231359533-0ab4be6f-b1e0-4268-9bcb-b49099af2efa.png)

**Comment by iMountTai** [comment]
所以本机还要安装visual studio才可以实现吗？

**Comment by josStorer** [comment]
这我不确定, 我是用vs编译的

**Comment by iMountTai** [comment]
好的，谢谢~
